spring:
  profiles:
    active: dev
  application:
#    name: microservice-base-generator
    name: pay-config
app:
  id: ${spring.application.name}
server:
  port: 8080
apollo:
  bootstrap:
    enabled: true
    namespaces: application,application.yml,db
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.fei.base.dao.model

  data:
    redis:
      database: 0
      host: "localhost"
      password: 123456
      port: 6379
      timeout: 10s
      pool:
        max-active: 20
        max-idle: 8
        max-wait: 3000
        min-idle: 0